### ISSUE TITLE
Client.Timeout or context cancellation while reading body

### ISSUE THREAD

**Issue by xuatseg** [rakyll/openai-go#14]
https://github.com/rakyll/openai-go/blob/3c4e9fb5a90611ce64db2d75da85345abc560960/openai.go#L40

Can we increase the timeout period or set the environmental variable? Sometimes there will be a timeout when encountering extensive data.
```text
Failed to complete: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```

**Comment by rakyll** [comment]
You can provide a custom timeout by using a custom HTTPClient.

```
sess := openai.NewSession(....)
sess.HTTPClient = &http.Client{
         Timeout: 120 * time.Second,
}
```
